### ISSUE TITLE
Вопрос по тестированию проекта

### ISSUE THREAD

**Issue by Mako-D** [czertyaka/prosoft-c-stack#21]
Судя по CMakeLists.txt, пока что GTest не ставится автоматически на комп. Это будет исправляться или CTest в приоритете? 

P.S.
Вроде бы гугл говорит, как линковать библиотеку через ссылку на github, но у меня этот вариант не работает.
https://google.github.io/googletest/quickstart-cmake.html

**Comment by czertyaka** [comment]
> или CTest в приоритете?

На всякий случай, чтобы не возникла путаница:
1. ctest - утилита для удобного запуска юнит-тестов, является частью cmake, устанавливается автоматически вместе с ним. По крайней мере, обратного я пока не встречал. Если у вас установлен cmake, то ctest с большой вероятностью тоже уже установлен.
2. GTest - один из вариантов названия GoogleTest. Это уже библиотека, то есть один или несколько ELF/dll файлов, а не утилита.
Т.е. это не конкурирующие инструменты. GTest нужен для сборки тестов, а ctest их запускает.

> Вроде бы гугл говорит, как линковать библиотеку через ссылку на github, но у меня этот вариант не работает.
https://google.github.io/googletest/quickstart-cmake.html

То, что вы прислали по ссылке, реализовано в файле [cmake/gtest.cmake](https://github.com/czertyaka/prosoft-c-stack/blob/master/cmake/gtest.cmake). В нем как раз скачивается библиотека через ``FetchContent_*``:

```cmake
include(FetchContent)
FetchContent_Declare(
	googletest
	# Specify the commit you depend on and update it regularly.
	URL https://github.com/google/googletest/archive/5376968f6948923e2411081fd9372e71a59d8e77.zip
)
# For Windows: Prevent overriding the parent project's compiler/linker settings
set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(googletest)
```

Обратите внимание, что этот файл подключается из [CMakeLists.txt](https://github.com/czertyaka/prosoft-c-stack/blob/master/CMakeLists.txt), только если не найден уже установленный GTest.
```cmake
    find_package(GTest)
    if (NOT ${GTest_FOUND})
        include(cmake/gtest.cmake)
    endif()
```

Сейчас попробовал собрать проект по инструкции в docker-образу операционной системы Ubuntu, в которой GTest не установлен. Вроде все работает:
<details>
    <summary>Вывод консоли</summary>
  <tt>root@e3a6fc8dfbeb:~# cmake src/ -B build -DWITH_TEST=ON
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find Python (missing: Python_EXECUTABLE Interpreter)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /root/build
root@e3a6fc8dfbeb:~# cmake --build build/
[  8%] Building C object CMakeFiles/cstack.dir/cstack.c.o
[ 16%] Linking C static library libcstack.a
[ 16%] Built target cstack
[ 25%] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 33%] Linking CXX static library ../../../lib/libgtest.a
[ 33%] Built target gtest
[ 41%] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 50%] Linking CXX static library ../../../lib/libgtest_main.a
[ 50%] Built target gtest_main
[ 58%] Building CXX object _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 66%] Linking CXX static library ../../../lib/libgmock.a
[ 66%] Built target gmock
[ 75%] Building CXX object _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 83%] Linking CXX static library ../../../lib/libgmock_main.a
[ 83%] Built target gmock_main
[ 91%] Building CXX object CMakeFiles/cstack_test.dir/test.cpp.o
[100%] Linking CXX executable cstack_test
[100%] Built target cstack_test</tt>
</details>

Если пробовали по инструкции и не получилось, или если вашего случая нет в инструкциях, можете поделиться проблемой, попробуем разобраться.

**Comment by Mako-D** [comment]
Большое спасибо за ответ!
Изначально меня смутило сообщение
```
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
``` 
из-за чего я подумал, что GTest не ставится, но не заметил, что дальше у нас идет добавление этой библиотеки при сборке. Отдельное спасибо за пояснения по устройству сборки проекта, а также за объяснение разницы между CTest и GTest. 

Проект собрал, тесты прогоняются.
