### ISSUE TITLE
Изменение порядка стеков после высвобождения одного из стеков в хендлере

### ISSUE THREAD

**Issue by Mako-D** [czertyaka/prosoft-c-stack#25]
Возник вопрос по ТЗ. Нужно ли смещать номера стеков в хендлере при удалении стека из него?

Пример,
```c++
stack_t a = stack_new(); // 0
stack_t b = stack_new(); // 1
stack_free(a);
```
После освобождения стек, который до освобождения был 1, должен после освобождения стать 0 или по прежнему остаться 1?

---
upd (если индексация должна сохраняться): Как должен вести себя хендлер после добавления нового стека, если стек 0 был освобождён, а 1 ещё занят? 
```c++
stack_t a = stack_new(); // 0
stack_t b = stack_new(); // 1
stack_free(a);
stack_t c = stack_new(); // 0 или 2?
```
То есть он всегда должен создавать стек с уникальным номером или должен индексировать минимальный свободный и занимать его?

**Comment by czertyaka** [comment]
Добрый день.

> Нужно ли смещать номера стеков в хендлере при удалении стека из него?

Смещать ни в коем случае нельзя:
```c
stack_t a = stack_new(); // 0
stack_t b = stack_new(); // 1
stack_free(a); // индекс второго стека теперь стал 0, а b - по прежнему равен 1
int a = 0;
stack_push(b, &a, sizeof(a)); // функция не отработает как надо
```
С точки зрения пользователя это вполне нормальный код. Но библиотека "втайне" поменяла хэндлеры и все поломалось.

> Как должен вести себя хендлер после добавления нового стека, если стек 0 был освобождён, а 1 ещё занят?

Тут ТЗ вас не ограничивает. Оба варианта возможны, вы должны выбрать лучший по вашему мнению)
